spring:
  application:
    name: Cart
  datasource:
    url: jdbc:mysql://localhost:3306/threadora
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: aman@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  aop:
    proxy-target-class: true
      
#spring.aop.proxy-target-class=true

server:
  port: 8084
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8000/eureka/
      
resilience4j:
  retry:
    instances:
      breaker1:
        max-attempts: 5
        wait-duration: 2s
