spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: Admin
          uri: lb://Admin
          predicates:
            - Path=/adm/**
            
  application:
    name: Gateway
server:
  port: 5454
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8000/eureka/
