spring:
  application:
    name: Payment
  datasource:
    url: jdbc:mysql://localhost:3306/threadora
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: aman@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8087
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8000/eureka/